controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
error_404:
    path: /404
    controller: App\Controller\ErrorController::show404

    
